# Generated by Django 4.1.4 on 2023-01-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
