# Generated by Django 4.1.4 on 2023-01-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
