# Generated by Django 4.1.4 on 2023-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='state',
            field=models.CharField(blank=True, max_length=150, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='zipcode',
            field=models.CharField(blank=True, max_length=150, verbose_name='zipcode'),
        ),
    ]
