# Generated by Django 4.1.4 on 2023-01-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopper_address_shopper_city_shopper_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='city',
        ),
    ]
