# Generated by Django 4.1.4 on 2023-01-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_shopper_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='city'),
        ),
    ]
