# Generated by Django 4.1.4 on 2023-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopper_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='device',
            field=models.CharField(blank=True, max_length=150, verbose_name='device'),
        ),
    ]
